name: Variable
run-name: saludos desde variable

on: push 

jobs:
  saludos:
    runs-on: ubuntu-latest
    steps:
      - name: manda un saludo
        run: echo "$MENSAJE_SECRETO" 
      - name: debbug de env
        run: echo "${{ toJSON(env) }}"
      - name: debbug de vars
        run: echo "${{ toJSON(vars) }}"
